In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
datasets=pd.get_dummies(dataset,drop_first=True)

In [5]:
datasets

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
datasets.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
indep=datasets[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dep=datasets[['charges']]

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train

array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]])

In [11]:
X_test

array([[ 0.89108031, -0.07576237, -0.0755796 ,  1.01127431, -0.49929923],
       [ 0.5336223 , -0.21009861, -0.0755796 , -0.98885138, -0.49929923],
       [ 0.6051139 ,  1.60182214,  0.75672907,  1.01127431,  2.00280702],
       ...,
       [-1.46814257,  0.65256665,  0.75672907, -0.98885138,  2.00280702],
       [-0.82471815,  0.37742013,  1.58903774,  1.01127431, -0.49929923],
       [ 0.89108031,  1.24817794,  0.75672907, -0.98885138, -0.49929923]])

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],
'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']}
2
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)

# fitting the model for grid search
grid.fit(X_train, y_train)

C:\Users\SRIRAM\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    2.6s
[Parallel(n_jobs=-1)]: Done  50 out of  54 | elapsed:    2.8s remaining:    0.1s
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:    2.8s finished
C:\Users\SRIRAM\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [13]:
# print best parameter after tuning
#print(grid.best_params_)
re=grid.cv_results_


print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'best'}:

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005319,4.700217e-04,0.002992,7.018853e-07,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.539366,0.674957,0.693507,0.635835,0.068746,4
1,0.004322,4.706398e-04,0.003658,4.692349e-04,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.676324,0.704945,0.636545,0.672609,0.028032,2
2,0.005985,4.899036e-07,0.003657,9.402682e-04,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.506089,0.431414,0.616177,0.517880,0.075848,17
3,0.004321,4.700217e-04,0.002661,4.705277e-04,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.686841,0.553621,0.592299,0.611005,0.055984,10
4,0.004986,4.052337e-07,0.002992,8.141015e-04,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.628290,0.078737,0.602492,0.436721,0.253140,18
5,0.003325,4.695731e-04,0.002659,9.403270e-04,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.547681,0.608297,0.639986,0.598598,0.038312,13
6,0.020279,4.700779e-03,0.002992,8.143934e-04,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.685076,0.642708,0.693708,0.673844,0.022278,1
7,0.013630,9.400996e-04,0.002327,4.700217e-04,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.560737,0.661131,0.662703,0.628115,0.047728,6
8,0.010971,8.135178e-04,0.001995,2.973602e-07,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.559442,0.455922,0.564317,0.526597,0.049973,16
9,0.009973,2.154866e-03,0.002660,4.701344e-04,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.564749,0.628501,0.654222,0.615767,0.037629,8
10,0.010638,4.697969e-04,0.001662,4.701903e-04,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.626045,0.600119,0.649141,0.625103,0.020013,7
11,0.008311,4.699655e-04,0.001663,4.700779e-04,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.676905,0.601160,0.531646,0.603320,0.059338,11
12,0.002327,4.700217e-04,0.000997,5.150430e-07,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.528290,0.673602,0.695918,0.632487,0.074361,5
13,0.001995,5.947204e-07,0.001330,4.704150e-04,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.655492,0.614067,0.637997,0.635874,0.016983,3
14,0.002992,8.133227e-04,0.001330,4.697408e-04,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.451823,0.671416,0.682858,0.601864,0.106376,12
15,0.002328,4.699093e-04,0.001330,4.696285e-04,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.526619,0.562755,0.593144,0.560801,0.027201,14
16,0.002660,4.701340e-04,0.000997,4.495664e-07,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.594134,0.648129,0.604923,0.615704,0.023328,9
17,0.002327,4.699655e-04,0.000997,2.247832e-07,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.481077,0.519437,0.610229,0.536852,0.054157,15

In [16]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:29
BMI:25
Children:0
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [17]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[63770.42801]